/*
 * anx/cell_trace.h — Execution Cell Trace (RFC-0003 Section 24).
 *
 * A Cell Trace is the append-only execution record generated by a cell.
 * It records timing, routing decisions, tool/model invocations,
 * validation results, and commit records.
 */

#ifndef ANX_CELL_TRACE_H
#define ANX_CELL_TRACE_H

#include <anx/types.h>

#define ANX_MAX_TRACE_EVENTS	64
#define ANX_CELL_TRACE_SCHEMA "anx:schema/cell-trace/v2"
#define ANX_CELL_TRACE_SCHEMA_VERSION "2"

/* --- Trace event types --- */

enum anx_trace_event_type {
	ANX_TRACE_CREATED,		/* description: intent name at runtime entry */
	ANX_TRACE_ADMITTED,
	ANX_TRACE_PLAN_GENERATED,
	ANX_TRACE_STEP_STARTED,
	ANX_TRACE_STEP_COMPLETED,
	ANX_TRACE_STEP_FAILED,
	ANX_TRACE_VALIDATION_PASS,
	ANX_TRACE_VALIDATION_FAIL,
	ANX_TRACE_COMMITTED,
	ANX_TRACE_RETRY,
	ANX_TRACE_CANCELLED,
	ANX_TRACE_FAILED,
	ANX_TRACE_COMPLETED,
	ANX_TRACE_ADMISSION_DENIED,
	ANX_TRACE_IDENTITY_COMMITMENT,	/* description: signed commitment record OID */
	ANX_TRACE_EFFECT_FENCE,		/* description: fence OID and epoch */
};

enum anx_admission_gate {
	ANX_ADMISSION_NONE,
	ANX_ADMISSION_SCOPE,
	ANX_ADMISSION_DESCRIPTOR,
	ANX_ADMISSION_AUTHORITY,
	ANX_ADMISSION_AUDIT_REQUIRED,
	ANX_ADMISSION_AUDIT_STORAGE,
	ANX_ADMISSION_IDENTITY,
	ANX_ADMISSION_EFFECT_FENCE,
	ANX_ADMISSION_TOOL_NAMESPACE,
	ANX_ADMISSION_EXECUTION_CONTRACT,
	ANX_ADMISSION_SCHEDULER_DOMAIN,
	ANX_ADMISSION_BRANCH_SCOPE,
	ANX_ADMISSION_CONTINUATION_GROUP,
};

/* --- Trace event --- */

struct anx_trace_event {
	uint32_t event_index;
	enum anx_trace_event_type type;
	anx_time_t timestamp;
	char description[128];
	int status_code;		/* result code for this event */
};

/* --- The Cell Trace --- */

struct anx_tool_accounting {
	bool attempted;
	anx_time_t started_at;
	anx_time_t completed_at;
	uint32_t request_bytes;
	uint32_t response_bytes;
	int transport_result;
	int status_code;
};

struct anx_cell_trace {
	anx_tid_t trace_id;
	anx_cid_t cell_ref;		/* cell this trace belongs to */
	anx_cid_t parent_cell_ref;	/* parent cell (nil if root) */
	anx_pid_t plan_ref;		/* plan used (nil if unplanned) */

	struct anx_trace_event events[ANX_MAX_TRACE_EVENTS];
	uint32_t event_count;

	anx_time_t started_at;
	anx_time_t completed_at;

	struct anx_tool_accounting tool;
	enum anx_admission_gate denied_gate;
	anx_oid_t storage_oid;
	bool finalized;			/* true after cell completes */
};

/* --- Trace API --- */

/* Create a trace for a cell */
int anx_trace_create(const anx_cid_t *cell_ref, struct anx_cell_trace **out);

/* Append an event to the trace */
int anx_trace_append(struct anx_cell_trace *trace,
		     enum anx_trace_event_type type,
		     const char *description,
		     int status_code);

/* Finalize a trace (materializes as execution_trace State Object) */
int anx_trace_finalize(struct anx_cell_trace *trace, anx_oid_t *trace_oid_out);

/* Reserve the full trace object before an external handler may run. */
int anx_trace_prepare(struct anx_cell_trace *trace);

#if defined(ANX_RESEARCH_TEST) || defined(ANX_HOST_TEST)
void anx_trace_test_fail_reservation(bool fail);
void anx_trace_test_fail_finalize(bool fail);
#endif

/* Destroy a trace */
void anx_trace_destroy(struct anx_cell_trace *trace);

#endif /* ANX_CELL_TRACE_H */
