#!/usr/bin/env python3
"""Rasterize the pinned theme fonts into fixed 12x24 ASCII kernel tables."""

import argparse
import hashlib
from pathlib import Path

import PIL
from PIL import Image, ImageDraw, ImageFont, features

ROOT = Path(__file__).resolve().parents[1]
WIDTH, HEIGHT, BASELINE = 12, 24, 19
FIRST, LAST = 0x20, 0x7E
POINT_SIZE, SUPERSAMPLE = 20, 4
PILLOW_VERSION, FREETYPE_VERSION = "12.3.0", "2.14.3"
FONTS = (
    ("AtkinsonHyperlegibleMono-Regular.ttf", "Atkinson Hyperlegible Mono",
     "2c9a7b9fabebd5c746a808d8a1ef2f52e618850caad6ec4fd9f5c48f56e1c1af"),
    ("CascadiaMono-Regular.ttf", "Cascadia Mono",
     "06520d032ec274fa5040b22c6f4a1d829081b24ba40b2da56dae89bf10c7b481"),
    ("JetBrainsMonoNerdFont-Regular.ttf", "JetBrainsMono NF",
     "1c680e8cde9fcf8b88a5605ce8d1fb94dd3fb15841f7ca7bf4c55664855e5611"),
)


def rasterize(filename, family, digest):
    path = ROOT / "system-font/sources" / filename
    if hashlib.sha256(path.read_bytes()).hexdigest() != digest:
        raise ValueError(f"source font hash mismatch: {filename}")
    font = ImageFont.truetype(path, POINT_SIZE * SUPERSAMPLE,
                             layout_engine=ImageFont.Layout.BASIC)
    if font.getname() != (family, "Regular"):
        raise ValueError(f"unexpected font family/style: {font.getname()}")
    if len({font.getlength(chr(code)) for code in range(FIRST, LAST + 1)}) != 1:
        raise ValueError(f"ASCII advance is not monospaced: {filename}")
    origin = 96
    source = []
    bounds = []
    for code in range(FIRST, LAST + 1):
        image = Image.new("L", (192, 192))
        ImageDraw.Draw(image).text((origin, origin), chr(code), font=font,
                                  fill=255, anchor="ls")
        box = image.getbbox()
        if box:
            if min(box[:2]) == 0 or max(box[2:]) == 192:
                raise ValueError(f"source glyph clipped: {filename} U+{code:04X}")
            bounds.append(tuple(value - origin for value in box))
        elif code != FIRST:
            raise ValueError(f"missing glyph: {filename} U+{code:04X}")
        source.append(image)
    left = min(box[0] for box in bounds)
    top = min(box[1] for box in bounds)
    right = max(box[2] for box in bounds)
    bottom = max(box[3] for box in bounds)
    # One uniform transform per face preserves bearings and proportions.
    # A quarter-pixel margin accounts for interpolation at the ink boundary.
    scale = min(1 / SUPERSAMPLE, (WIDTH - 0.5) / (right - left),
                (BASELINE - 0.25) / -top, (HEIGHT - BASELINE - 0.25) / bottom)
    offset_x = (WIDTH - (right - left) * scale) / 2 - left * scale
    glyphs, bits = [], []
    border = 2
    for code, image in enumerate(source, FIRST):
        # Render beyond the cell as well, then reject any lost nonzero coverage.
        rendered = image.transform(
            (WIDTH + 2 * border, HEIGHT + 2 * border), Image.Transform.AFFINE,
            (1 / scale, 0, origin - (offset_x + border) / scale,
             0, 1 / scale, origin - (BASELINE + border) / scale),
            resample=Image.Resampling.BICUBIC)
        box = rendered.getbbox()
        if box and (box[0] < border or box[1] < border or
                    box[2] > WIDTH + border or box[3] > HEIGHT + border):
            raise ValueError(f"destination glyph clipped: {filename} U+{code:04X}")
        cell = rendered.crop((border, border, WIDTH + border, HEIGHT + border))
        alpha = list(cell.get_flattened_data())
        rows = [sum((alpha[y * WIDTH + x] >= 128) << (WIDTH - 1 - x)
                    for x in range(WIDTH)) for y in range(HEIGHT)]
        if code != FIRST and not any(rows):
            raise ValueError(f"glyph vanished at threshold 128: {filename} U+{code:04X}")
        if code == FIRST and any(alpha):
            raise ValueError(f"space is not blank: {filename}")
        glyphs.append(alpha)
        bits.append(rows)
    print(f"{family}: Regular; ASCII fixed advance; effective {POINT_SIZE * SUPERSAMPLE * scale:.3f}px; baseline {BASELINE}")
    return glyphs, bits


def header(alpha, bits):
    lines = [
        "/* Generated by tools/gen_theme_fonts.py; do not edit.",
        " * Font data: SIL Open Font License 1.1; see system-font/licenses/.",
        " * Copyright 2020-2024 The Atkinson Hyperlegible Mono Project Authors.",
        " * Copyright (c) 2019 - Present, Microsoft Corporation.",
        " * Copyright 2020 The JetBrains Mono Project Authors.",
        " * Copyright (c) 2014, Ryan L McIntyre (Nerd Fonts).",
        f" * Rasterizer: Pillow {PILLOW_VERSION}, FreeType {FREETYPE_VERSION}.",
        " * Order: Atkinson Hyperlegible Mono, Cascadia Mono, JetBrainsMono Nerd Font.",
        " */", "#ifndef ANX_THEME_FONT_DATA_H", "#define ANX_THEME_FONT_DATA_H",
        "", "#include <anx/types.h>", "",
        "static const uint8_t anx_theme_font_alpha[3][95][24 * 12] = {",
    ]
    for (filename, _, _), glyphs in zip(FONTS, alpha):
        lines.append(f"\t{{ /* {filename} */")
        for code, glyph in enumerate(glyphs, FIRST):
            lines.append(f"\t\t{{ /* U+{code:04X} */")
            for y in range(HEIGHT):
                lines.append("\t\t\t" + ",".join(str(n) for n in glyph[y * WIDTH:(y + 1) * WIDTH]) + ",")
            lines.append("\t\t},")
        lines.append("\t},")
    lines.extend(("};", "", "static const uint16_t anx_theme_font_bits[3][95][24] = {"))
    for (filename, _, _), glyphs in zip(FONTS, bits):
        lines.append(f"\t{{ /* {filename} */")
        for code, glyph in enumerate(glyphs, FIRST):
            lines.append("\t\t{" + ",".join(f"0x{row:03x}" for row in glyph) + f"}}, /* U+{code:04X} */")
        lines.append("\t},")
    lines.extend(("};", "", "#endif /* ANX_THEME_FONT_DATA_H */", ""))
    return "\n".join(lines)


def preview(path, alpha):
    scale, panel_width, block_height = 2, 480, 390
    image = Image.new("RGB", (1020, block_height * len(FONTS)), "#e7ebf0")
    draw = ImageDraw.Draw(image)
    label_font = ImageFont.load_default(size=18)
    for face, (_, family, _) in enumerate(FONTS):
        top = face * block_height
        draw.text((20, top + 10), family + " - Regular, 12x24", fill="#172033", font=label_font)
        for mono in range(2):
            left = 20 + mono * 500
            draw.text((left, top + 38), "Threshold 128" if mono else "Grayscale coverage",
                      fill="#172033", font=label_font)
            grid = Image.new("L", (panel_width // scale, 5 * HEIGHT), 255)
            for index, glyph in enumerate(alpha[face]):
                pixels = [0 if n >= 128 else 255 for n in glyph] if mono else [255 - n for n in glyph]
                cell = Image.new("L", (WIDTH, HEIGHT))
                cell.putdata(pixels)
                grid.paste(cell, ((index % 19) * WIDTH, (index // 19) * HEIGHT))
            image.paste(grid.resize((panel_width, 5 * HEIGHT * scale), Image.Resampling.NEAREST), (left, top + 64))
            for row, text in enumerate(("O0 Il1 !| gqj {}[] <> _-~= 0123456789", "Anunix: The quick brown fox jumps.")):
                for col, char in enumerate(text):
                    glyph = alpha[face][ord(char) - FIRST]
                    cell = Image.new("L", (WIDTH, HEIGHT))
                    cell.putdata([0 if n >= 128 else 255 for n in glyph] if mono else [255 - n for n in glyph])
                    image.paste(cell, (left + col * WIDTH, top + 318 + row * HEIGHT))
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "kernel/include/anx/theme_font_data.h")
    parser.add_argument("--preview", type=Path)
    parser.add_argument("--check", action="store_true", help="compare generated bytes without writing")
    args = parser.parse_args()
    try:
        if PIL.__version__ != PILLOW_VERSION or features.version_module("freetype2") != FREETYPE_VERSION:
            raise ValueError(f"reproduction needs Pillow {PILLOW_VERSION} / FreeType {FREETYPE_VERSION}")
        faces = [rasterize(*font) for font in FONTS]
        alpha, bits = zip(*faces)
        text = header(alpha, bits)
        if args.check:
            if args.output.read_bytes() != text.encode("utf-8"):
                raise ValueError("generated font header differs; regenerate with the pinned rasterizer")
        else:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(text, encoding="utf-8", newline="\n")
        if args.preview:
            preview(args.preview, alpha)
    except (OSError, ValueError) as error:
        parser.exit(1, f"theme fonts: {error}\n")


if __name__ == "__main__":
    main()
