#!/usr/bin/env python3
"""Generate WPA2-PSK handshake vectors for tests/test_mt7925.c.

Plays the authenticator with Python's hashlib/hmac and the cryptography
package's RFC 3394 key wrap, independently of the kernel's crypto, and
writes the frames an Anunix station must accept and the replies it must
produce byte for byte:

    python3 tools/gen_wpa_vectors.py > tests/harness/mt7925_wpa_vectors.h
"""
import hashlib
import hmac
import struct

from cryptography.hazmat.primitives.keywrap import aes_key_wrap

PASSPHRASE = b"correct horse battery"
SSID = b"Anunix-Test"
AA = bytes.fromhex("020000aa0001")
SPA = bytes.fromhex("020000bb0002")
ANONCE = bytes(range(0x10, 0x30))
SNONCE = bytes(range(0x80, 0xa0))
GTK1 = bytes.fromhex("00112233445566778899aabbccddeeff")
GTK2 = bytes.fromhex("f0e0d0c0b0a090807060504030201000")

# Our RSN element: CCMP group, CCMP pairwise, PSK.
STA_RSN = bytes.fromhex("30140100000fac040100000fac040100000fac020000")
# The AP's element, as a beacon would carry it (with capabilities 0x000c).
AP_RSN = bytes.fromhex("30140100000fac040100000fac040100000fac020c00")


def prf(key, label, data, nbytes):
    out = b""
    i = 0
    while len(out) < nbytes:
        out += hmac.new(key, label + b"\x00" + data + bytes([i]),
                        hashlib.sha1).digest()
        i += 1
    return out[:nbytes]


def eapol_key(info, key_len, replay, nonce, key_data, version=2):
    body = struct.pack(">BHH", 2, info, key_len)
    body += struct.pack(">Q", replay)
    body += nonce + bytes(16) + bytes(8) + bytes(8) + bytes(16)
    body += struct.pack(">H", len(key_data)) + key_data
    return struct.pack(">BBH", version, 3, len(body)) + body


def with_mic(frame, kck):
    mic = hmac.new(kck, frame, hashlib.sha1).digest()[:16]
    return frame[:81] + mic + frame[97:]


def gtk_kde(gtk, idx):
    return bytes([0xdd, 6 + len(gtk)]) + bytes.fromhex("000fac01") + \
        bytes([idx, 0]) + gtk


def wrap(kek, data):
    # RFC 3394 needs a multiple of 8 and at least 16; pad as 802.11 says.
    if len(data) % 8 or len(data) < 16:
        data += b"\xdd"
        while len(data) % 8 or len(data) < 16:
            data += b"\x00"
    return aes_key_wrap(kek, data)


def c_array(name, data):
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
        lines.append(f"\t{chunk},")
    lines.append("};")
    return "\n".join(lines)


def main():
    pmk = hashlib.pbkdf2_hmac("sha1", PASSPHRASE, SSID, 4096, 32)
    data = min(AA, SPA) + max(AA, SPA) + min(ANONCE, SNONCE) + \
        max(ANONCE, SNONCE)
    ptk = prf(pmk, b"Pairwise key expansion", data, 48)
    kck, kek, tk = ptk[:16], ptk[16:32], ptk[32:48]

    # IEEE 802.11-2020 J.4.2 test vector for the PBKDF2 step itself.
    ieee = hashlib.pbkdf2_hmac("sha1", b"password", b"IEEE", 4096, 32)
    assert ieee.hex() == ("f42c6fc52df0ebef9ebb4b90b38a5f90"
                          "2e83fe1b135a70e23aed762e9710a12e")

    pmkid_kde = bytes.fromhex("dd14000fac04") + bytes(range(16))
    m1 = eapol_key(0x008a, 16, 1, ANONCE, pmkid_kde)

    m2 = with_mic(eapol_key(0x010a, 0, 1, SNONCE, STA_RSN, version=1), kck)

    m3_plain = AP_RSN + gtk_kde(GTK1, 1)
    m3 = with_mic(eapol_key(0x13ca, 16, 2, ANONCE, wrap(kek, m3_plain)), kck)

    m4 = with_mic(eapol_key(0x030a, 0, 2, bytes(32), b"", version=1), kck)

    g1 = with_mic(eapol_key(0x1382, 16, 3, bytes(32),
                            wrap(kek, gtk_kde(GTK2, 2))), kck)
    g2 = with_mic(eapol_key(0x0302, 0, 3, bytes(32), b"", version=1), kck)

    # A message 3 whose MIC is wrong must be dropped.
    m3_bad = bytearray(m3)
    m3_bad[81] ^= 0x01

    print("/* Generated by tools/gen_wpa_vectors.py. Do not edit. */")
    print("#ifndef MT7925_WPA_VECTORS_H")
    print("#define MT7925_WPA_VECTORS_H")
    print()
    print('#define WPA_V_PASSPHRASE "' + PASSPHRASE.decode() + '"')
    print('#define WPA_V_SSID "' + SSID.decode() + '"')
    for name, value in [("wpa_v_aa", AA), ("wpa_v_spa", SPA),
                        ("wpa_v_snonce", SNONCE), ("wpa_v_sta_rsn", STA_RSN),
                        ("wpa_v_pmk", pmk), ("wpa_v_ptk", ptk),
                        ("wpa_v_tk", tk), ("wpa_v_gtk1", GTK1),
                        ("wpa_v_gtk2", GTK2),
                        ("wpa_v_m1", m1), ("wpa_v_m2", m2),
                        ("wpa_v_m3", m3), ("wpa_v_m3_bad", bytes(m3_bad)),
                        ("wpa_v_m4", m4), ("wpa_v_g1", g1),
                        ("wpa_v_g2", g2)]:
        print(c_array(name, value))
        print()
    print("#endif")


if __name__ == "__main__":
    main()
