#!/usr/bin/env python3
"""Generate the embedded boot-secrets header.

Reads an untracked local file of `name = value` lines and emits a C header the
kernel compiles in. When the file is absent -- which is the normal case, and
the case for every build anyone else makes -- the header declares an empty
table and the kernel embeds nothing.

The input file is gitignored. The output lands under build/, which is also
gitignored. Neither can reach the repository through an ordinary commit.

This exists for bringing a machine onto a network before it has any other way
to be configured. A kernel built this way carries its Wi-Fi password in
plaintext in the image; see the warning the kernel prints at boot.
"""

import argparse
import os
import sys

ALLOWED = {"wifi-ssid", "wifi-pass"}


def c_escape(s: str) -> str:
    out = []
    for ch in s:
        if ch in ('"', "\\"):
            out.append("\\" + ch)
        elif " " <= ch <= "~":
            out.append(ch)
        else:
            out.append("\\x%02x" % ord(ch))
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True)
    ap.add_argument("--header", required=True)
    args = ap.parse_args()

    entries = []
    if os.path.exists(args.input):
        with open(args.input, "r", encoding="utf-8") as fh:
            for lineno, raw in enumerate(fh, 1):
                line = raw.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" not in line:
                    sys.stderr.write(
                        "%s:%d: expected name = value\n" % (args.input, lineno))
                    return 1
                name, value = line.split("=", 1)
                name = name.strip()
                value = value.strip()
                if name not in ALLOWED:
                    sys.stderr.write(
                        "%s:%d: '%s' is not an injectable name (allowed: %s)\n"
                        % (args.input, lineno, name, ", ".join(sorted(ALLOWED))))
                    return 1
                entries.append((name, value))

    os.makedirs(os.path.dirname(args.header), exist_ok=True)
    with open(args.header, "w", encoding="utf-8") as out:
        out.write("/* Generated by tools/gen_boot_secrets.py. Do not edit. */\n")
        out.write("#ifndef ANX_BOOT_SECRETS_H\n#define ANX_BOOT_SECRETS_H\n\n")
        out.write("struct anx_boot_secret {\n\tconst char *name;\n"
                  "\tconst char *value;\n};\n\n")
        out.write("static const struct anx_boot_secret anx_boot_secrets[] = {\n")
        for name, value in entries:
            out.write('\t{ "%s", "%s" },\n' % (c_escape(name), c_escape(value)))
        out.write("\t{ 0, 0 }\n};\n\n")
        out.write("#define ANX_BOOT_SECRET_COUNT %d\n\n" % len(entries))
        out.write("#endif /* ANX_BOOT_SECRETS_H */\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
