/*
 * font.c — ANX Schoolbook 12×24 bitmap font.
 *
 * Century Schoolbook-inspired design: bracketed half-serifs,
 * 2-px thick stems, moderate stroke contrast.  Covers printable
 * ASCII (0x20–0x7E).  Each glyph is 24 uint16_t rows;
 * bit 11 (0x800) is the leftmost pixel.
 *
 * Glyph data generated by system-font/gen_anx_font.py.
 */

#include <anx/types.h>
#include <anx/font.h>
#include <anx/fb.h>
#include <anx/anx_schoolbook_12x24.h>

/* Fallback glyph for characters outside 0x20-0x7E: filled block */
static const uint16_t glyph_fallback[ANX_FONT_HEIGHT] = {
	0xFFF, 0xFFF, 0xFFF, 0xFFF, 0xFFF, 0xFFF, 0xFFF, 0xFFF,
	0xFFF, 0xFFF, 0xFFF, 0xFFF, 0xFFF, 0xFFF, 0xFFF, 0xFFF,
	0xFFF, 0xFFF, 0xFFF, 0xFFF, 0xFFF, 0xFFF, 0xFFF, 0xFFF,
};

const uint16_t *anx_font_glyph(char c)
{
	unsigned char uc = (unsigned char)c;

	if (uc < ANX_FONT12_FIRST || uc > ANX_FONT12_LAST)
		return glyph_fallback;

	return anx_font12[uc - ANX_FONT12_FIRST];
}

void anx_font_draw_char(uint32_t x, uint32_t y,
			char c, uint32_t fg, uint32_t bg)
{
	const uint16_t *glyph = anx_font_glyph(c);
	uint32_t row;

	for (row = 0; row < ANX_FONT_HEIGHT; row++) {
		uint16_t bits = glyph[row];
		uint32_t col;

		for (col = 0; col < ANX_FONT_WIDTH; col++) {
			/* bit 11 = leftmost; shift right by (11 - col) */
			uint32_t color = (bits & (0x800u >> col)) ? fg : bg;

			anx_fb_putpixel(x + col, y + row, color);
		}
	}
}
